<?xml version="1.0" encoding="UTF-8" ?>

        <!-- DTD INTERNO -->
<!--
<!DOCTYPE nota [
<!ELEMENT nota (para,de,titulo,contenido)*>
<!ELEMENT para (#PCDATA)>
<!ELEMENT de (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
]>
-->

        <!-- DTD EXTERNO -->
        <!DOCTYPE nota SYSTEM "documento1.dtd">
<!-- elemento raiz y su contenido-->
<nota>
    <para>Pedro</para>
    <de>Laura</de>
    <titulo>Recordatorio</titulo>
    <contenido>A las 7:00 en la puerta del teatro</contenido>
</nota>